/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6795. Copyright MediaTek Inc. (C) 2013.
 * Sat Mar  5 11:44:13 2016
 * Do Not Modify the File.
 */

#define CUST_EINT_MD_LEVEL_SENSITIVE        0
#define CUST_EINT_MD_EDGE_SENSITIVE         1




#define PAD_INT_SIM1            0
#define PAD_INT_SIM2            1
#define PAD_SPI_MO            2
#define PAD_SPI_CS            3
#define PAD_URXD0            4
#define PAD_URTS0            5
#define PAD_URXD3            6
#define PAD_DPI_D0            7
#define PAD_DPI_D2            8


#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD1_0_NAME             "MD1_SIM1_HOT_PLUG_EINT"
#define CUST_EINT_MD1_0_NUM              0
#define CUST_EINT_MD1_0_DEBOUNCE_CN      100
#define CUST_EINT_MD1_0_POLARITY         CUST_EINT_POLARITY_HIGH
#define CUST_EINT_MD1_0_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_0_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE
#define CUST_EINT_MD1_0_DEDICATED_EN      0
#define CUST_EINT_MD1_0_SRCPIN             PAD_INT_SIM1

#define CUST_EINT_MD1_1_NAME             "MD1_SIM2_HOT_PLUG_EINT"
#define CUST_EINT_MD1_1_NUM              1
#define CUST_EINT_MD1_1_DEBOUNCE_CN      100
#define CUST_EINT_MD1_1_POLARITY         CUST_EINT_POLARITY_HIGH
#define CUST_EINT_MD1_1_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD1_1_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE
#define CUST_EINT_MD1_1_DEDICATED_EN      0
#define CUST_EINT_MD1_1_SRCPIN             PAD_INT_SIM2

#define CUST_EINT_MD1_CNT      2


